name: ci_unit_test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
           pip install flake8 pytest black

      - name: Check formatting with black
        run: black --check --line-length 120 src tests

      - name: Lint with flake8
        run: flake8 src tests --max-line-length=120

      - name: Run tests
        run: pytest tests -v
